
version: '3'
services:
  frontend-ovoz:
    image: feruzjon/ovoz:latest
    deploy:
      replicas: 2
      placement:
        constraints: [node.role==worker]
    ports:
      - "5000:80"
    networks:
      - frontend
    deploy:
      placement:
        constraints: [node.role==worker]
  frontend-natija:
    image: feruzjon/natija:latest
    ports:
      - "5001:80"
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role==worker]
  backend:
    image: feruzjon/backend:latest
    networks:
      - frontend
      - backend
    deploy:
      replicas: 2
      placement:
        constraints: [node.role==worker]
  redis:
    image: redis:alpine
    networks:
      - frontend
    deploy:
      placement:
        constraints: [node.role==worker]
  db:
    image: postgres:15-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    deploy:
      replicas: 2
      placement:
        constraints: [node.role==worker]
  visualizer:
    image: dockersamples/visualizer
    ports:
    - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role==manager]
networks:
  frontend:
  backend:
volumes:
  db-data:
