version: "3"
services:
 redis:
  image: redis:alpine
  deploy:
   placement:
     constraints:
      - node.role==worker
  networks:
   - frontend
 db:
  image: postgres:15-alpine
  deploy:
   placement:
     constraints:
      - node.role==worker
  networks:
   - backend
  volumes:
   - db-data:/var/lib/postgresql/data
  environment:
   POSTGRES_USER: "postgres"
   POSTGRES_PASSWORD: "postgres"
 frontend-ovoz:
  image: feruzjon/ovoz:latest
  ports:
   - "5000:80"
  networks:
   - frontend
  deploy:
    replicas: 2
    placement:
     constraints:
      - node.role==worker
 frontend-natija:
  image: feruzjon/natija:latest
  ports:
   - "5001:80"
  networks:
   - backend
  deploy:
   placement:
    constraints:
     - node.role==worker
 backend:
  image: feruzjon/backend:latest
  networks:
   - frontend
   - backend
  deploy:
    replicas: 2
    placement:
     constraints:
      - node.role==worker
networks:
 frontend:
 backend:
volumes:
 db-data:
  driver: local
